### ISSUE TITLE
Remove Rajat's name from the paper 

### ISSUE THREAD

**Issue by Ayushk4** [Snehal-Reddy/ML_RRT_Star_APF#12]
Remove Rajat's name from acknowledgements and thereby removing his name from the paper.
https://github.com/Snehal-Reddy/ML_RRT_Star_APF/blob/d57f695462c3003ee0a6585f2b03acc17db5a508/Research%20Paper/paper.tex#L288

**Comment by Ayushk4** [comment]
@RKJenamani :stuck_out_tongue:

**Comment by Snehal-Reddy** [comment]
Sure ! Thinking of the same actually !
